### ISSUE TITLE
Github へのプッシュお作法

### ISSUE THREAD

**Issue by massanex** [massanex/ark#11]
githubにarkレポジトリを作成する。
ソースツリーを使ってmassanex/ark を windows ローカルの /lo_ws/vagrant_ark_dir_data に clone する。
vagrant 内の /home/vagrant/ark を /lo_ws/ark_dir_data と同期させる設定をしておく。
ソースツリーのdevelopでブランチを切る。例えば topic/0.0.1/xxxxx とか。
arkディレクトリ内でファイル編集を行う。
ソースツリーの topic/0.0.1/xxxxx で、コミットを行う。
ソースツリーの topic/0.0.1/xxxxx で、プッシュを行う。
github の ark のページでブランチの項目にプッシュの反映がされているのでプルリクエストボタンを押す。
プルリクエストの項目に項目が上がってくるのでマージボタンを押すとマスターに反映される。

**Comment by Konboi** [comment]
local ディレクトリ以下はバージョン管理しない方がいいですね

開発環境が(mac, linux)で異なったりするので
バージョン固定とかはcpanfileでやるべきですね

**Comment by massanex** [comment]
表記例がよくないてすね。
ブランチ切って何やってるか分かるように名前をつけるという意味合いです。

**Comment by Konboi** [comment]
いや､自分の説明が言葉足りずでした...

https://github.com/massanex/ark/tree/master/Jobeet/local

この依存モジュールがインストールされているディレクトリ以下もaddされていますが､実際のプロジェクトでは各人の開発環境が(mac, linux)で異なったりするのでモジュールのバージョン管理はcpanfileに記述して

deployサーバーでインストールして & それを各webサーバーに撒くのがよくあるパターンですね

**Comment by massanex** [comment]
了解です。
しかしgit rm local しようとしたらエラーが。

**Comment by massanex** [comment]
git rm -rf local とかしました
